[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "brewjanitor"
version = "0.1.0"
description = "Tool that brings the software on your Mac into the fold of Homebrew."
readme = "README.md"
requires-python = ">=3.9"

[project.scripts]
brewjanitor = "brewjanitor.cli:main"

[tool.setuptools.packages.find]
include = ["brewjanitor*"]
